object frmInputHelper: TfrmInputHelper
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmInputHelper'
  ClientHeight = 24
  ClientWidth = 400
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 13
end
